name: Запуск тестов Java/TestNG/Maven

on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID - service parameter (leave blank)
        required: false
      ALLURE_USERNAME:
        description: ALLURE_USERNAME - service parameter (leave blank)
        required: false
      BROWSER:
        required: true
        default: Google Chrome
      ENDPOINT: 
        required: true
        default: Demo
      OS:
        required: true
        default: Windows    
      VERSION:
        required: true
        default: '5.16.0'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'

      - name: Get the latest allurectl
        run: |
          latest_version=$(curl -s https://api.github.com/repos/allure-framework/allurectl/releases/latest | jq -r .tag_name)
          echo "ALLURECTL_VERSION=$latest_version" >> $GITHUB_ENV

      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://demo.testops.cloud/
          allure-project-id: 3111
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allurectl-version: ${{ env.ALLURECTL_VERSION }}

      - name: Run tests with Maven
        run: |
          mvn clean test
          allurectl watch -- mvn clean test
        env:
          ALLURE_RESULTS: "target/allure-results"
          ALLURE_TESTPLAN_PATH: "./testplan.json"
          BRANCH: ${{ github.ref_name }}
          BROWSER: ${{ inputs.BROWSER }}
          ENDPOINT: ${{ inputs.ENDPOINT }}
          OS: ${{ inputs.OS }}
          VERSION: ${{ inputs.VERSION }}
